### ISSUE TITLE
A part of a design has different background in Sketch

### ISSUE THREAD

**Issue by petrbrzek** [avocode/psd-to-sketch-converter#1]
Original design link: 
https://app.avocode.com/view/4c1b4704ec52459e9b6b232a0ef6fa45/11281030/comments/

### Expected behavior

Screenshot from Photoshop:

![3_psd___100___layer_2__rgb_8____](https://user-images.githubusercontent.com/879564/26877242-91516676-4b89-11e7-9ee1-d17f9e73a024.png)
  
### Actual behavior

Screenshot from Sketch (bottom part should not be gray):
![3_sketch](https://user-images.githubusercontent.com/879564/26877267-a17a293e-4b89-11e7-9e8f-5017b9b4ad12.png)

**Comment by czertbytes** [comment]
The issue is already fixed. Please re-test in upcoming release 0.5.0
