### ISSUE TITLE
i've entered my email - but not getting the download link?

### ISSUE THREAD

**Issue by faz-kamisan** [avocode/psd-to-sketch-converter#13]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

What are you reporting?

### Expected behavior

Tell us what you think should happen.

### Actual behavior

Tell us what actually happens. If possible, also upload a screenshot to show what's broken or missing.

**Comment by MattRoskovec** [comment]
Hey, sorry, we're having some troubles with downloading bitmap images from our server which sometimes makes the conversion crash. However, you should always receive an e-mail - even when the conversion fails to complete.

Can you please send me a name of the uploaded PSD design so I can look into it? 

In the meantime, please try converting a different design and let me know if it worked. Thank you.

**Comment by thejoelcook** [comment]
I also had this issue, no email after the file was uploaded. I believe my file was: Thankyou_Landing.psd

Not sure if there is a size limit for the psd upload but I think my file was close to 50mb.

**Comment by czertbytes** [comment]
The issue is already fixed. Please re-test in upcoming release 0.5.0

**Comment by janbernd** [comment]
I also had this issue, no email after the file was uploaded. I believe my file was: test.psd
