### ISSUE TITLE
Wrong color in shadows

### ISSUE THREAD

**Issue by helloiamvu** [avocode/psd-to-sketch-converter#2]
### Design name

converter-bug.psd

### Description

The color of the shadow in Photoshop is different from the color in Sketch.
This is the RGB code for the shadow in:

Photoshop: 0, 78, 255
Sketch: 78,0,255

The green color in PSD is translated to Sketch as red. That's the bug.

Screenshot in PSD:
![screenshot 2017-06-07 17 03 56](https://user-images.githubusercontent.com/3011660/26885888-27b6d87a-4ba4-11e7-9d47-27684806f1d5.png)

Screenshot in Sketch:
![screenshot 2017-06-07 17 06 10](https://user-images.githubusercontent.com/3011660/26885897-2e672eae-4ba4-11e7-82e3-8dbca3674f7a.png)

**Comment by czertbytes** [comment]
Fixed in commit 6480f9af
