### ISSUE TITLE
Your design could not be processed - Even with simple file with 5 layers

### ISSUE THREAD

**Issue by jardicc** [avocode/psd-to-sketch-converter#38]
[test.zip](https://github.com/avocode/psd-to-sketch-converter/files/1700477/test.zip)

I am always recieve e-mail "Your design could not be processed" Even with simple file with 5 layers

**Comment by rexmulholland** [comment]
I am having the same problem which I didn't experience on the 1st to 3rd day of using it even with multiple layer psd with styles.

**Comment by HybridCap** [comment]
same issue - there's nothing different between this file and the file I converted 3 days ago  - but still not working.

**Comment by bicharacho** [comment]
Same here, I did a test on week ago, and today I am receiving the same error message. All the layers are simple text, or shape layers. the same kind of file that I tested before

**Comment by rimasalb** [comment]
Same here :(

**Comment by jardicc** [comment]
Bolek from Avocode said that they know it and could it fix it today.

**Comment by bolekkerous** [comment]
Hey guys, the converter should work again. :)

**Comment by bicharacho** [comment]
thank you @bolekkerous
