### ISSUE TITLE
Crooked text layers

### ISSUE THREAD

**Issue by MattRoskovec** [avocode/psd-to-sketch-converter#4]
### Design name

Guacamole-UI-kit.sketch

### Description

Text layers look crooked.

### Expected behavior

Correct text layer display and line height.

### Actual behavior

https://www.dropbox.com/s/24a9otepij2i8ks/Screenshot%202017-06-07%2018.09.49.png?dl=0

**Comment by czertbytes** [comment]
The issue is already fixed. Please re-test in upcoming release 0.5.0
