### ISSUE TITLE
Font sizes change

### ISSUE THREAD

**Issue by eduardochang** [avocode/psd-to-sketch-converter#5]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Design name

Post for facebook

### Description

What are you reporting?

### Expected behavior

Font sizes maintain size

### Actual behavior

Font sizes get jumbled, position is fine. 

![artboard](https://user-images.githubusercontent.com/1088025/26939165-b10d5808-4c33-11e7-8a9e-4283003a3722.png)

**Comment by czertbytes** [comment]
The issue is already fixed. Please re-test in upcoming release 0.5.0
