### ISSUE TITLE
Email not receive from psd to sketch converter

### ISSUE THREAD

**Issue by komsikov** [avocode/psd-to-sketch-converter#50]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

What are you reporting?

### Expected behavior

Tell us what you think should happen.

### Actual behavior

Tell us what actually happens. If possible, also upload a screenshot to show what's broken or missing.

**Comment by hadasamshalem** [comment]
Design Name: shait_product
Description: I didnet get the sketch file to my email

**Comment by janbernd** [comment]
Design Name: test.psd
Description: I didn't get the sketch file to my email
