### ISSUE TITLE
Text layers don't break (one line instead of small box)

### ISSUE THREAD

**Issue by grmon** [avocode/psd-to-sketch-converter#6]
### Design name

01-einsparpotentiale-tablet.psd / .sketch

### Description

Text stays in one line (see gray text in screenshot)

### Expected behavior

Text layer width should be imported

### Actual behavior

Text boxes don't keep width

<img width="312" alt="bildschirmfoto 2017-06-09 um 09 12 18" src="https://user-images.githubusercontent.com/500813/26965001-3d20cac6-4cf4-11e7-9460-a1ace4b9879a.png">

**Comment by austin-guevara** [comment]
Related to this is that it doesn't respect line breaks. I.e. in Photoshop if you do shift+enter to break and go to the next line, the converted Sketch file does not show this. Instead, it puts all the text on the same line.

**Comment by czertbytes** [comment]
The issue is already fixed. Please re-test in upcoming release 0.5.0
